//! Conformance: the brand-motion artefacts, and the one animation behind them.
//!
//! ADR 0012 emits the same motion twice — Lottie for the desktop, animated SVG
//! for the web — and says plainly why that needs a gate: *"without the pin it
//! would be two animations that merely resemble each other."*
//!
//! **This file is one half of that pin, and it is not the byte-for-byte half.**
//! The artefacts are generated by `motion/build_form.py`, which is Python, so
//! the "regenerate and diff" check the crate's emitters get from
//! `cargo run --example dump_css` lives in `scripts/check-motion.sh` and runs in
//! CI. What is here is the half a byte comparison cannot do: a snapshot only
//! ever proves that a file has not changed, and every claim below is about what
//! the file has to *be*.
//!
//! So each test names a way the two could drift apart while both still played:
//! a mark that is nearly the tracked one, a colour that is nearly a token, a
//! loop that is nearly the same length, a theme that has quietly been redrawn
//! rather than recoloured.

use meridian_design::brand;

/// The four artefacts, with the mode whose tokens they may draw from.
const ARTEFACTS: &[(&str, &str, bool)] = &[
    ("form.svg", brand::MOTION_FORM_SVG, false),
    ("form_dark.svg", brand::MOTION_FORM_SVG_DARK, true),
    ("form.json", brand::MOTION_FORM_LOTTIE, false),
    ("form_dark.json", brand::MOTION_FORM_LOTTIE_DARK, true),
];

const SVGS: &[(&str, &str, bool)] = &[
    ("form.svg", brand::MOTION_FORM_SVG, false),
    ("form_dark.svg", brand::MOTION_FORM_SVG_DARK, true),
];

/// Every value of `attr` in a document, in order.
fn attrs<'a>(doc: &'a str, attr: &str) -> Vec<&'a str> {
    let needle = format!(" {attr}=\"");
    doc.match_indices(&needle)
        .map(|(at, _)| {
            doc[at + needle.len()..]
                .split_once('"')
                .expect("an attribute value is quoted")
                .0
        })
        .collect()
}

/// The first `"key":` number in a JSON document.
///
/// The Lottie's own `op` and `fr` are the first of each: `build_form.py` writes
/// the composition header before any layer, and `json.dumps` keeps insertion
/// order. Every later `"op"` belongs to a layer.
fn first_number(json: &str, key: &str) -> f64 {
    let needle = format!("\"{key}\":");
    let rest = &json[json.find(&needle).expect("key present") + needle.len()..];
    let end = rest
        .find(|c: char| !c.is_ascii_digit() && c != '.' && c != '-')
        .unwrap_or(rest.len());
    rest[..end].parse().expect("a number")
}

/// The `<style>` block of an SVG document.
fn style(svg: &str) -> &str {
    svg.split_once("<style>")
        .expect("the artefact carries a style block")
        .1
        .split_once("</style>")
        .expect("a closed style block")
        .0
}

/// The top-level rules of a stylesheet, as `(prelude, body)`.
///
/// Brace depth rather than a split on `}`, so an `@media` block comes back as
/// one rule with its own rules inside it instead of as fragments.
fn rules(css: &str) -> Vec<(&str, &str)> {
    let (mut out, mut depth, mut start, mut open) = (Vec::new(), 0usize, 0usize, 0usize);
    for (at, c) in css.char_indices() {
        match c {
            '{' => {
                if depth == 0 {
                    open = at;
                }
                depth += 1;
            }
            '}' => {
                depth -= 1;
                if depth == 0 {
                    out.push((css[start..open].trim(), &css[open + 1..at]));
                    start = at + 1;
                }
            }
            _ => {}
        }
    }
    assert_eq!(depth, 0, "unbalanced braces in a stylesheet");
    out
}

/// Where each of the mark's six subpaths begins, walked out of the tracked
/// path itself.
///
/// The mark is a chain: `M300,100`, then five relative `m` moves, each taken
/// from where `Z` left the pen — which is the subpath's *own* start, not its
/// end. Walking it is the only way to know what an absolute opening move
/// should say, and knowing that is the difference between checking that the
/// teeth are the right shape and checking that they are in the right place.
fn tooth_origins() -> Vec<(f32, f32)> {
    let mut pen = (0.0f32, 0.0f32);
    brand::mark_path()
        .expect("the mark has path data")
        .split_terminator('Z')
        .map(|sub| {
            let head = sub.trim();
            let (kind, rest) = head.split_at(1);
            let (x, y) = rest
                .split_once('l')
                .expect("a tooth opens with a move and then a line")
                .0
                .split_once(',')
                .expect("a move is a pair");
            let (x, y) = (x.parse::<f32>().unwrap(), y.parse::<f32>().unwrap());
            pen = match kind {
                "M" => (x, y),
                "m" => (pen.0 + x, pen.1 + y),
                other => panic!("the mark opens a subpath with {other:?}"),
            };
            pen
        })
        .collect()
}

/// The token values a mode may legitimately use, as lower-case hex.
///
/// **Dark inherits from light**, which is the CSS cascade and not a
/// convenience: `.dark` redefines a subset of `:root` and deliberately leaves
/// the chart ramps alone, because a data ramp is the same ramp whichever theme
/// surrounds it. The dark artefact's wake walks `--m-seq`, which is declared in
/// `:root` only — read the two blocks as independent sets and this test would
/// call the shipped file off-palette.
fn palette(dark: bool) -> std::collections::HashSet<String> {
    let css = meridian_design::emit::tokens_css();
    let (light_block, dark_block) = css.split_once("\n.dark {").expect("two mode blocks");
    let mut named = std::collections::HashMap::new();
    let mut read = |block: &str| {
        for line in block.lines() {
            if let Some((name, value)) = line.trim().split_once(": ") {
                if name.starts_with("--") {
                    named.insert(name.to_owned(), value.trim_end_matches(';').to_owned());
                }
            }
        }
    };
    read(light_block);
    if dark {
        read(dark_block);
    }
    named
        .into_values()
        .filter(|v| v.starts_with('#'))
        .map(|v| v.to_ascii_lowercase())
        .collect()
}

/// The animated SVG draws the mark that is in `brand/`, to the character.
///
/// The teeth are not re-serialised from the Lottie's floats — they are the
/// tracked `d` attribute's own text, so this can compare strings rather than
/// coordinates, and a re-export that moved a control point fails here as well
/// as in `brand.rs`.
///
/// One thing is allowed to differ, and only one. The six subpaths of the mark
/// are a chain: the first opens `M300,100` and the rest open with a *relative*
/// `m` taken from where `Z` left the pen. A row that draws teeth 5 and 4 on
/// their own breaks that chain, so each subpath's opening move is rewritten
/// absolute. Everything after it is untouched, which is why the comparison
/// starts at the first `l` — the same seam `brand.rs` compares the padded mark
/// across.
#[test]
fn the_animated_svg_draws_the_tracked_mark() {
    let mut canonical: Vec<&str> = brand::mark_path()
        .expect("the mark has path data")
        .split_terminator('Z')
        .map(|sub| sub.split_once('l').expect("a tooth has a relative line").1)
        .collect();
    assert_eq!(canonical.len(), 6, "the mark is six teeth");
    canonical.sort_unstable();

    for (name, svg, _) in SVGS {
        // A row is the only filled thing in the file; the strokes carry no
        // fill. So every `d` on an element that also carries `fill=` is teeth.
        let rows: Vec<&str> = svg
            .match_indices("<path")
            .map(|(at, _)| {
                let element = &svg[at..at + svg[at..].find("/>").expect("a closed element")];
                assert!(
                    !element.contains(" fill=\"") || !element.contains(" stroke=\""),
                    "{name}: an element that both fills and strokes"
                );
                element
            })
            .filter(|element| element.contains(" fill=\""))
            .map(|element| {
                element
                    .split_once(" d=\"")
                    .expect("a path has data")
                    .1
                    .split_once('"')
                    .unwrap()
                    .0
            })
            .collect();
        assert!(!rows.is_empty(), "{name} draws no teeth at all");

        let subpaths: Vec<&str> = rows
            .iter()
            .flat_map(|d| {
                let subs: Vec<&str> = d.split_terminator('Z').collect();
                assert_eq!(subs.len(), 2, "{name}: a row of the mark is two teeth");
                subs
            })
            .collect();

        // The shape: everything after the opening move is the file's own text.
        let mut teeth: Vec<&str> = subpaths
            .iter()
            .map(|sub| {
                assert!(
                    sub.starts_with('M'),
                    "{name}: a tooth opens relative, so where it lands depends on \
                     whichever tooth a row happens to draw before it"
                );
                sub.split_once('l').expect("a tooth has a relative line").1
            })
            .collect();
        teeth.sort_unstable();
        teeth.dedup();
        assert_eq!(
            teeth, canonical,
            "{name} does not draw the mark in brand/meridian_black.svg"
        );

        // The placement: the opening move is the one part rewritten, so it is
        // the one part a text comparison cannot check. Every origin the file
        // uses has to be an origin the mark's own chain arrives at.
        let origins = tooth_origins();
        for sub in &subpaths {
            let (x, y) = sub[1..]
                .split_once('l')
                .unwrap()
                .0
                .split_once(',')
                .expect("an absolute move is a pair");
            let at = (x.parse::<f32>().unwrap(), y.parse::<f32>().unwrap());
            assert!(
                origins.contains(&at),
                "{name} opens a tooth at {at:?}, which is not where that tooth \
                 sits in brand/meridian_black.svg — the right shape, moved"
            );
        }
    }
}

/// Nothing in either artefact is a picked colour.
///
/// This is the check the animation spent most of its life failing. The leader's
/// ink was a literal for the whole exploration — `#1a1917` on light, `#e9e6e0`
/// on dark — and neither is a token value. They were close enough to `--m-ink`
/// to look right in every review, and the mark beside them was never the same
/// colour. That is ADR 0011's shadow palette arriving in a generator instead of
/// in an app, which is the reason this gate reads the emitted CSS rather than
/// a list written here.
#[test]
fn every_colour_in_the_artefacts_is_a_token_value() {
    for (name, svg, dark) in SVGS {
        let allowed = palette(*dark);
        let used: Vec<&str> = attrs(svg, "stroke")
            .into_iter()
            .chain(attrs(svg, "fill"))
            .filter(|v| v.starts_with('#'))
            .collect();
        assert!(used.len() >= 4, "{name}: only {} inks?", used.len());
        for colour in used {
            assert!(
                allowed.contains(&colour.to_ascii_lowercase()),
                "{name} uses {colour}, which is not a token value in that mode — \
                 a generator has started picking colours"
            );
        }
    }
}

/// The Lottie carries the same inks as the SVG beside it, and no others.
///
/// The SVG's colours are checked against the palette above; this ties the other
/// format to them. Lottie stores colour as `[r, g, b, a]` floats, so the two
/// files cannot be compared as text — but they can be counted, and an ink that
/// exists in one format and not the other is exactly the drift ADR 0012 asks
/// for a pin against.
#[test]
fn the_two_formats_carry_the_same_number_of_inks() {
    for (svg_name, svg, dark) in SVGS {
        let mut inks: Vec<String> = attrs(svg, "stroke")
            .into_iter()
            .chain(attrs(svg, "fill"))
            .filter(|v| v.starts_with('#'))
            .map(str::to_owned)
            .collect();
        inks.sort();
        inks.dedup();

        let (json_name, json, _) = ARTEFACTS
            .iter()
            .find(|(n, _, d)| n.ends_with(".json") && d == dark)
            .expect("each theme has both formats");
        let colours = json.matches("\"c\":{\"a\":0,\"k\":[").count();
        let distinct: std::collections::HashSet<&str> = json
            .match_indices("\"c\":{\"a\":0,\"k\":[")
            .map(|(at, m)| {
                let rest = &json[at + m.len()..];
                &rest[..rest.find(']').expect("a closed colour array")]
            })
            .collect();
        assert!(colours > 0, "{json_name} declares no colour at all");
        // The mattes are filled black to punch an alpha channel, and that is
        // not ink — one extra value, in every theme.
        assert_eq!(
            distinct.len(),
            inks.len() + 1,
            "{json_name} carries {} distinct colours against {svg_name}'s {} inks \
             (plus the mattes' black); one format has gained or lost one",
            distinct.len(),
            inks.len()
        );
    }
}

/// Both formats loop for the same length of time.
///
/// The Lottie states it as frames over a frame rate and the SVG as a CSS
/// duration, so this is the one number that has to survive the translation and
/// the one a re-choreographing emitter would get wrong first.
#[test]
fn the_two_formats_agree_on_the_loop() {
    for (svg_name, svg, dark) in SVGS {
        let (_, json, _) = ARTEFACTS
            .iter()
            .find(|(n, _, d)| n.ends_with(".json") && d == dark)
            .unwrap();
        let seconds = first_number(json, "op") / first_number(json, "fr");
        let expected = format!("{seconds}s");

        // Every duration in the file, not merely one of them. The animation
        // loops as a whole, so a single element on a different clock does not
        // run slightly wrong — it drifts out of phase with the rest and never
        // comes back.
        let mut found: Vec<&str> = Vec::new();
        for (_, body) in rules(style(svg)) {
            for decl in body.split(';') {
                let Some(list) = decl.trim().strip_prefix("animation:") else {
                    continue;
                };
                found.extend(
                    list.split(',')
                        .filter_map(|one| one.split_whitespace().nth(1)),
                );
            }
        }
        assert!(!found.is_empty(), "{svg_name} declares no animation at all");
        for duration in &found {
            assert_eq!(
                *duration, expected,
                "{svg_name} runs something for {duration}, where the Lottie's \
                 op/fr comes to {expected} — the two formats are different lengths"
            );
        }
        assert!(
            !svg.contains("animation-duration"),
            "{svg_name} sets a duration outside the shorthand, where this test \
             cannot see it"
        );
    }
}

/// Reduced motion is honoured, and only inside the artefact.
///
/// ADR 0012 requires it and `guidelines/speed.md` requires it of anything that
/// moves. The scoping half matters because an inlined SVG's `<style>` applies
/// to the whole host document: an unscoped `*{animation:none}` would stop every
/// animation on the page around it, which is a bug shaped exactly like a
/// feature working.
#[test]
fn the_animated_svg_stops_for_reduced_motion() {
    for (name, svg, _) in SVGS {
        assert!(
            svg.contains("prefers-reduced-motion:reduce"),
            "{name} moves and never asks whether it should"
        );
        let root = svg
            .split_once(" id=\"")
            .expect("the root carries an id to scope by")
            .1
            .split_once('"')
            .unwrap()
            .0;
        assert!(
            svg.contains(&format!("#{root} *{{animation:none!important}}")),
            "{name}'s reduced-motion rule is not scoped to its own root"
        );

        let scoped = |selector: &str| selector.starts_with(&format!("#{root}"));
        let mut checked = 0;
        for (prelude, body) in rules(style(svg)) {
            if prelude.starts_with("@keyframes") {
                continue; // percentages, not selectors
            }
            for selector in if prelude.starts_with("@media") {
                rules(body).into_iter().map(|(s, _)| s).collect::<Vec<_>>()
            } else {
                vec![prelude]
            } {
                checked += 1;
                assert!(
                    scoped(selector),
                    "{name} carries an unscoped rule {selector:?}. An inlined SVG's \
                     <style> applies to the whole host document, so this would \
                     restyle the page around it"
                );
            }
        }
        assert!(
            checked > 1,
            "{name}: only {checked} selectors seen — parse error?"
        );
    }
}

/// Light and dark are the same drawing in different ink.
///
/// Strip the hex and the two files are byte-identical. That is a stronger claim
/// than "they look similar": it says the geometry, the schedule, every keyframe
/// percentage and every delay came from one source, and that a theme cannot be
/// quietly redrawn while wearing the same name.
#[test]
fn the_dark_form_is_the_light_form_recoloured() {
    let strip = |svg: &str, slug: &str| {
        let mut out = svg.replace(slug, "meridian-form");
        while let Some(at) = out.find('#') {
            let hex = out[at..]
                .chars()
                .take_while(|c| c.is_ascii_hexdigit() || *c == '#')
                .count();
            if hex == 7 {
                out.replace_range(at..at + 7, "\u{0}");
            } else {
                // A selector, not a colour. Step over it and keep looking.
                let next = out[at + 1..].find('#').map(|n| at + 1 + n);
                match next {
                    Some(_) => out.replace_range(at..at + 1, "\u{1}"),
                    None => break,
                }
            }
        }
        out
    };
    assert_eq!(
        strip(brand::MOTION_FORM_SVG, "meridian-form"),
        strip(brand::MOTION_FORM_SVG_DARK, "meridian-form-dark"),
        "the dark form has been redrawn rather than recoloured"
    );
}

/// Every artefact is on the mark's own canvas.
#[test]
fn the_artefacts_share_the_marks_canvas() {
    let side = brand::MARK_VIEWBOX as u32;
    for (name, doc, _) in ARTEFACTS {
        let on_canvas = doc.contains(&format!("viewBox=\"0 0 {side} {side}\""))
            || doc.contains(&format!("\"w\":{side},\"h\":{side}"));
        assert!(
            on_canvas,
            "{name} is not on the mark's {side}x{side} canvas, so it cannot be \
             swapped for a static mark at the same size"
        );
    }
}

/// The web artefact needs no runtime, and fetches nothing.
///
/// This is the whole reason the format split in ADR 0012 is asymmetric: the
/// site ships no motion library and has already done deliberate work to stop
/// fetching one from a CDN. An artefact that reached for a script or an
/// external asset would put that cost straight back.
#[test]
fn the_web_artefact_is_self_contained() {
    for (name, svg, _) in SVGS {
        for reach in ["<script", "href=", "src=", "url(http", "@import", "<image"] {
            assert!(
                !svg.contains(reach),
                "{name} contains {reach:?} — the web takes this file precisely \
                 because it costs one request and no runtime"
            );
        }
    }
}
