//! Emitters — every downstream artefact is generated from this crate and
//! pinned by a conformance test (ADR 0008): `tokens.css` for the web, and
//! (Phase 1) the gpui-component `ThemeConfig` JSON pair for Brightfield.

use crate::MARITIME;

/// Emit the CSS custom-properties artefact. Deterministic by construction;
/// `tests/conformance.rs` pins the exact output. Phase 0 carries the brand
/// signature only — scales, semantic tokens, and dark values land in Phase 1.
pub fn tokens_css() -> String {
    let mut css = String::new();
    css.push_str("/* Generated by meridian-design — do not edit by hand. */\n");
    css.push_str(":root {\n");
    css.push_str(&format!("  --meridian-maritime: {};\n", MARITIME.hex()));
    css.push_str("}\n");
    css
}
