//! Emitters — every downstream artefact is generated from this crate and
//! pinned by a conformance test (ADR 0008): `tokens.css` for the web, and
//! the gpui-component `ThemeConfig` JSON pair for Brightfield.

mod theme;
pub use theme::{theme_config, ThemeMode};

use crate::chrome::{InkTokens, INK_DARK, INK_LIGHT};
use crate::colour::Rgba;
use crate::scales::*;
use crate::viz::*;

fn scale(css: &mut String, name: &str, s: &[Rgba; 12]) {
    for (i, c) in s.iter().enumerate() {
        css.push_str(&format!("  --m-{}-{}: {};\n", name, i + 1, c.hex()));
    }
}

fn ink(css: &mut String, t: &InkTokens) {
    css.push_str(&format!("  --m-surface: {};\n", t.surface.hex()));
    css.push_str(&format!("  --m-page: {};\n", t.page.hex()));
    css.push_str(&format!("  --m-ink: {};\n", t.ink_primary.hex()));
    css.push_str(&format!("  --m-ink-secondary: {};\n", t.ink_secondary.hex()));
    css.push_str(&format!("  --m-ink-muted: {};\n", t.ink_muted.hex()));
    css.push_str(&format!("  --m-gridline: {};\n", t.gridline.hex()));
    css.push_str(&format!("  --m-baseline: {};\n", t.baseline.hex()));
    css.push_str(&format!("  --m-focus: {};\n", t.focus.hex()));
}

fn mode_block(css: &mut String, dark: bool) {
    scale(css, "gray", if dark { &GRAY_DARK } else { &GRAY_LIGHT });
    scale(css, "maritime", if dark { &MARITIME_DARK } else { &MARITIME_LIGHT });
    scale(css, "red", if dark { &RED_DARK } else { &RED_LIGHT });
    scale(css, "amber", if dark { &AMBER_DARK } else { &AMBER_LIGHT });
    scale(css, "green", if dark { &GREEN_DARK } else { &GREEN_LIGHT });
    scale(css, "blue", if dark { &BLUE_DARK } else { &BLUE_LIGHT });
    let cat = if dark { &CATEGORICAL_DARK } else { &CATEGORICAL_LIGHT };
    for (i, c) in cat.iter().enumerate() {
        css.push_str(&format!("  --m-cat-{}: {};\n", i + 1, c.hex()));
    }
    css.push_str(&format!(
        "  --m-null-ink: {};\n",
        if dark { NULL_INK_DARK } else { NULL_INK_LIGHT }.hex()
    ));
    css.push_str(&format!(
        "  --m-div-mid: {};\n",
        if dark { DIVERGING_MID_DARK } else { DIVERGING_MID_LIGHT }.hex()
    ));
    ink(css, if dark { &INK_DARK } else { &INK_LIGHT });
}

/// Emit the CSS custom-properties artefact (light `:root`, dark under
/// `.dark`, matching the web repo's theme class). Deterministic by
/// construction; `tests/conformance.rs` pins the exact output.
pub fn tokens_css() -> String {
    let mut css = String::new();
    css.push_str("/* Generated by meridian-design — do not edit by hand. */\n");
    css.push_str(":root {\n");
    css.push_str(&format!("  --meridian-maritime: {};\n", crate::MARITIME.hex()));
    mode_block(&mut css, false);
    // Mode-invariant values.
    for (i, c) in SEQUENTIAL_MERIDIAN.iter().enumerate() {
        css.push_str(&format!("  --m-seq-{}: {};\n", 100 + i * 50, c.hex()));
    }
    for (i, c) in DIVERGING_BLUE_ARM.iter().enumerate() {
        css.push_str(&format!("  --m-div-blue-{}: {};\n", i + 1, c.hex()));
    }
    for (i, c) in DIVERGING_RED_ARM.iter().enumerate() {
        css.push_str(&format!("  --m-div-red-{}: {};\n", i + 1, c.hex()));
    }
    css.push_str(&format!("  --m-status-good: {};\n", STATUS.good.hex()));
    css.push_str(&format!("  --m-status-warning: {};\n", STATUS.warning.hex()));
    css.push_str(&format!("  --m-status-serious: {};\n", STATUS.serious.hex()));
    css.push_str(&format!("  --m-status-critical: {};\n", STATUS.critical.hex()));
    css.push_str("}\n.dark {\n");
    mode_block(&mut css, true);
    css.push_str("}\n");
    css
}
