#!/usr/bin/env python3
"""Assemble the published evidence site, and refuse to publish a broken one.

The repo already holds the pages that show its work — the palette review
gallery, and the preview and measurement harnesses the brand motion was built
against. Until now they were invisible without cloning and serving from the
repository root, which is a strange place to keep the evidence for decisions
the ADRs cite.

Three things this script does, in one place on purpose:

1. **Copies.** The site mirrors the repository layout rather than flattening
   it, because every preview page addresses its assets with paths like
   `../../meridian-design/brand/motion/form.svg`. Flattening would mean
   rewriting the pages for publication, and a page that is rewritten on the way
   out is no longer the page anyone tested.

2. **Writes the index from the same manifest it copies from.** One list, so the
   landing page cannot advertise something that was not published, nor omit
   something that was.

3. **Checks every reference resolves inside the built site**, and exits
   non-zero if one does not. A dangling `src` is invisible to every other gate
   here: the file is tracked, the HTML is valid, CI is green, and the page is
   quietly broken for everyone but the person who has the repo checked out.

Run it locally the same way CI does:

    python3 scripts/build-pages.py _site && python3 -m http.server -d _site
"""

from __future__ import annotations

import html
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The published pages, in the order the index lists them. The third field is
# what the page is *for* — these are working instruments, not polished demos,
# and saying so is more useful than dressing them up.
PAGES: list[tuple[str, str, str]] = [
    (
        "validation/gallery-2026-07-16.html",
        "Palette review gallery",
        "Every shipped palette as it was reviewed on 2026-07-16 — the categorical set in both "
        "modes, the sequential and diverging ramps, and the simulated colour-vision-deficiency "
        "passes the ordering was chosen by. The record behind ADR 0006.",
    ),
    (
        "motion/preview/lockup.html",
        "The lockup, forming",
        "The second capped brand asset, live in both themes, with a filmstrip driven off the "
        "page's own animation clock and the reduced-motion resting state beside it.",
    ),
    (
        "motion/preview/form.html",
        "The mark, forming",
        "The first capped asset, and the honest-work cue. Two players side by side so a scheme "
        "can be compared against the one that shipped.",
    ),
    (
        "motion/preview/svg.html",
        "SVG against Lottie, frame by frame",
        "The measurement harness behind ADR 0012's two-format claim: the emitted SVG and the "
        "Lottie it was generated from, stopped on the same frame. The two formats agree to "
        "seven significant figures, and this is where that was established.",
    ),
    (
        "motion/preview/ink.html",
        "Wake schemes and lags",
        "Every wake the generator can build, at both lags, all the same length so they can be "
        "stopped on the same frame. Filmstrips hide holes; this is what to open after a timing "
        "change.",
    ),
    (
        "motion/preview/schemes.html",
        "The schemes that lost",
        "The chosen scheme against its runner-up and against itself at a two-frame lag — what "
        "that knob costs, kept so the decision can be re-examined rather than re-argued.",
    ),
    (
        "motion/preview/orbit-check.html",
        "Orbit alignment",
        "The narrow check that the orbit's trim pair lands on the mark's own edges.",
    ),
]

# Everything the pages reach for. Directories are copied whole; the check below
# is what proves the list is sufficient, so this stays a starting point rather
# than a promise.
ASSETS: list[str] = [
    "meridian-design/brand/motion",  # the four tracked artefacts, both formats
    "motion/preview/lottie.min.js",  # vendored so the pages work offline
    "motion/output",  # regenerated by `build_form.py --explore`
    "motion/README.md",  # linked from the preview pages
]

# References a static site cannot resolve for us. `schemes.html` builds its
# filenames in a template literal, so the check below reads the page's own
# scheme list and asks for the files that list implies.
DYNAMIC = "motion/preview/schemes.html"


def tokens_css() -> str:
    """The emitted token block, with its dark half taught to follow the reader.

    `tokens.css` puts dark under a `.dark` class because that is what the web
    app toggles. A static page has nothing to toggle it, so the same block is
    repeated under `prefers-color-scheme` — repeated by reading it, not by
    restating it, which is the rule every other artefact here follows.
    """
    css = (ROOT / "meridian-design/tests/snapshots/tokens.css").read_text()
    _, _, dark = css.partition("\n.dark {")
    dark = dark.rstrip().removesuffix("}")
    return f"{css}\n@media (prefers-color-scheme: dark) {{\n  :root {{{dark}}}\n}}\n"


def index(pages: list[tuple[str, str, str]]) -> str:
    cards = "\n".join(
        f"""    <li>
      <a href="{html.escape(path)}">
        <h2>{html.escape(title)}</h2>
        <p>{html.escape(blurb)}</p>
        <code>{html.escape(path)}</code>
      </a>
    </li>"""
        for path, title, blurb in pages
    )
    return f"""<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Meridian Design System — evidence</title>
<style>
{tokens_css()}
* {{ box-sizing: border-box; }}
body {{
  margin: 0; padding: var(--m-space-7) var(--m-space-5);
  background: var(--m-surface-app); color: var(--m-text-primary);
  font-family: var(--m-font-sans), ui-sans-serif, system-ui, sans-serif;
  font-size: var(--m-font-size-ui); line-height: 1.6;
}}
main {{ max-width: 860px; margin: 0 auto; }}
picture img {{ width: 100%; max-width: 336px; height: auto; display: block; }}
h1 {{ font-size: 22px; font-weight: 600; margin: var(--m-space-6) 0 var(--m-space-2); }}
.lede {{ color: var(--m-text-secondary); margin: 0 0 var(--m-space-6); max-width: 62ch; }}
.lede a {{ color: var(--m-text-link); }}
ul {{ list-style: none; margin: 0; padding: 0; display: grid; gap: var(--m-space-3); }}
li a {{
  display: block; padding: var(--m-space-4);
  background: var(--m-surface-raised); color: inherit; text-decoration: none;
  border: 1px solid var(--m-border-subtle); border-radius: var(--m-radius-panel);
  transition: border-color var(--m-motion-spatial), background var(--m-motion-spatial);
}}
li a:hover {{ background: var(--m-rows-hover-bg); border-color: var(--m-border-strong); }}
li a:focus-visible {{
  outline: var(--m-focus-ring-width) solid var(--m-border-focus);
  outline-offset: var(--m-focus-ring-offset);
}}
h2 {{ font-size: 14px; font-weight: 600; margin: 0 0 var(--m-space-1); }}
li p {{ margin: 0 0 var(--m-space-2); color: var(--m-text-secondary); max-width: 68ch; }}
code {{
  font-family: var(--m-font-mono), ui-monospace, monospace;
  font-size: 11px; color: var(--m-text-muted);
}}
footer {{
  margin-top: var(--m-space-7); padding-top: var(--m-space-4);
  border-top: 1px solid var(--m-border-divider); color: var(--m-text-muted);
  max-width: 62ch;
}}
footer a {{ color: var(--m-text-link); }}
</style>
<main>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="meridian-design/brand/motion/lockup_dark.svg">
    <img src="meridian-design/brand/motion/lockup.svg" alt="Meridian">
  </picture>
  <h1>Evidence</h1>
  <p class="lede">
    The pages the Meridian design system was decided on: the palette review that
    ADR 0006 cites, and the harnesses the brand motion was measured with. They live in
    <a href="https://github.com/meridian-online/design">the repository</a> and were previously
    unreadable without cloning it. Nothing here is a polished demo — these are working
    instruments, published because the evidence for a decision is worth as much as the decision.
  </p>
  <ul>
{cards}
  </ul>
  <footer>
    <p>
      This page is styled by the system it documents: every colour, size and duration above is a
      custom property read from the crate's emitted <code>tokens.css</code>, not a value written
      here. For the values themselves see
      <a href="https://github.com/meridian-online/design/blob/main/reference/tokens.md">the token
      reference</a>; for the reasoning, <a
      href="https://github.com/meridian-online/design/tree/main/guidelines">the guidelines</a>.
    </p>
    <p>The mark and its motion are trademarks, reserved — not covered by the repository's MIT grant.</p>
  </footer>
</main>
</html>
"""


def local_refs(page: str) -> set[str]:
    """Every same-origin path a page asks for, as written."""
    refs: set[str] = set()
    refs |= set(re.findall(r"""(?:src|href)=["']([^"'>]+)""", page))
    refs |= set(re.findall(r"""url\(["']?([^)"']+)""", page))
    refs |= set(re.findall(r"""["'](\.\.?/[^"'`]+)["']""", page))
    return {
        r.split("#")[0].split("?")[0]
        for r in refs
        if not r.startswith(("http://", "https://", "//", "#", "data:", "mailto:"))
    }


def scheme_files(page: str) -> set[str]:
    """The scratch files `schemes.html`'s own scheme list implies.

    Its filenames are built in a template literal, so they cannot be read off
    the source the way a plain `src` can. Reading the list it iterates is the
    next best thing, and it is the half that actually drifts — the generator's
    scheme names and the page's have to agree.
    """
    block = re.search(r"const SCHEMES = \[(.*?)\];", page, re.S)
    if not block:
        return set()
    names = re.findall(r"""\[\s*['"]([^'"]+)['"]""", block.group(1))
    return {
        f"motion/output/form-{n}{suffix}.json" for n in names for suffix in ("", "-dark")
    }


def main() -> int:
    out = Path(sys.argv[1] if len(sys.argv) > 1 else "_site")
    if out.exists():
        shutil.rmtree(out)

    published = []
    for path, title, blurb in PAGES:
        source = ROOT / path
        if not source.is_file():
            sys.exit(f"build-pages: {path} is listed but not in the tree")
        published.append((path, title, blurb))
        (out / path).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, out / path)

    for asset in ASSETS:
        source = ROOT / asset
        target = out / asset
        if source.is_dir():
            shutil.copytree(source, target, dirs_exist_ok=True)
        elif source.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
        else:
            sys.exit(
                f"build-pages: {asset} is missing. If it is motion/output/, the "
                f"exploration scratch has not been built — run "
                f"`cd motion && python3 build_form.py --explore` first."
            )

    (out / "index.html").write_text(index(published))

    # Nothing is published until every reference in it resolves.
    broken: list[str] = []
    for path, _, _ in published + [("index.html", "", "")]:
        page = (out / path).read_text(encoding="utf-8", errors="replace")
        wanted = local_refs(page)
        if path == DYNAMIC:
            wanted |= {f"/{f}" for f in scheme_files(page)}
        for ref in sorted(wanted):
            here = (out / path).parent
            target = (out / ref.lstrip("/")) if ref.startswith("/") else (here / ref)
            if not target.resolve().exists():
                broken.append(f"  {path}  ->  {ref}")

    if broken:
        print("build-pages: references that would 404 once published:\n")
        print("\n".join(broken))
        return 1

    files = sum(1 for p in out.rglob("*") if p.is_file())
    size = sum(p.stat().st_size for p in out.rglob("*") if p.is_file())
    print(
        f"build-pages: {len(published)} pages, {files} files, "
        f"{size / 1024 / 1024:.1f} MB — every reference resolves."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
